groups:
  - name: alert.rules
rules:
  - alert: InstanceDown

# Condition for alerting
expr: up == 0
for: 2m
annotations:
title: 'Instance {{ $labels.instance }} down'
description: '{{ $labels.instance }} of job name {{ $labels.job }} has been down for more than 2 minutes.'
labels:
severity: 'critical'